<?php
/**
 * @file
 * Module file for miniOrange OAuth client Module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;


/**
* Implements hook_form_alter().
*/
function oauth_login_oauth2_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  global $base_url;
  if(!empty(\Drupal::config('oauth_login_oauth2.settings')->get('oauth_login_oauth2_base_url')))
    $baseUrlValue = \Drupal::config('oauth_login_oauth2.settings')->get('oauth_login_oauth2_base_url');
  else
    $baseUrlValue = $base_url;
  if(($form_id == 'user_login_block') || ($form_id == 'user_login_form'))
    {
      if(!empty(\Drupal::config('oauth_login_oauth2.settings')->get('miniorange_auth_client_app_name')))
      {
      $oauth_login_url = $baseUrlValue . '/moLogin';
      $server_name = \Drupal::config('oauth_login_oauth2.settings')->get('miniorange_auth_client_app_name');
      $form['loginurl']= array(array(
        '#markup' => '<a href="'. $oauth_login_url .'">Login using ' . $server_name . '</a>'
      ));
     }
    }
}
