oauth_login_oauth2.settings:
  type: mapping
  label: Settings
  mapping:
    oauth_login_oauth2_customer_admin_email:
      type: 'NULL'
    oauth_login_oauth2_license_key:
      type: 'NULL'
    oauth_login_oauth2_customer_id:
      type: string
    oauth_login_oauth2_customer_admin_token:
      type: string
    oauth_login_oauth2_customer_api_key:
      type: string
    oauth_login_oauth2_force_auth:
      type: boolean
    oauth_login_oauth2_enable_backdoor:
      type: boolean
    oauth_login_oauth2_default_relaystate:
      type: string
    oauth_login_oauth2_name:
      type: string
    oauth_login_oauth2_issuer:
      type: string
    oauth_login_oauth2_login_url:
      type: string
    oauth_login_oauth2_logout_url:
      type: string
    oauth_login_oauth2_x509_certificate:
      type: string
    oauth_login_oauth2_response_signed:
      type: boolean
    oauth_login_oauth2_assertion_signed:
      type: boolean
    oauth_login_oauth2_enable_login:
      type: boolean
    oauth_login_oauth2_username_attribute:
      type: string
    oauth_login_oauth2_email_attribute:
      type: string
    oauth_login_oauth2_attr1_name:
      type: string
    oauth_login_oauth2_attr5_name:
      type: string
    oauth_login_oauth2_attr5_name:
      type: string
    oauth_login_oauth2_attr2_name:
      type: string
    oauth_login_oauth2_attr2_name:
      type: string
    oauth_login_oauth2_attr3_name:
      type: string
    oauth_login_oauth2_attr3_name:
      type: string
    oauth_login_oauth2_attr4_name:
      type: string
    oauth_login_oauth2_attr4_name:
      type: string
    oauth_login_oauth2_disable_autocreate_users:
      type: boolean
    oauth_login_oauth2_default_role:
      type: string
    oauth_login_oauth2_role1_name:
      type: string
    oauth_login_oauth2_role1_name:
      type: string
    oauth_login_oauth2_role2_name:
      type: string
    oauth_login_oauth2_role2_name:
      type: string
    oauth_login_oauth2_role3_name:
      type: string
    oauth_login_oauth2_role3_name:
      type: string
    oauth_login_oauth2_role4_name:
      type: string
    oauth_login_oauth2_role4_name:
      type: string
    oauth_login_oauth2_status:
      type: string
    oauth_login_oauth2_customer_admin_phone:
      type: 'NULL'
    oauth_login_oauth2_tx_id:
      type: 'NULL'
    oauth_login_oauth2_customer_admin_password:
      type: string
    oauth_login_oauth2_auto_redirect_to_idp:
      type: boolean
    oauth_login_oauth2_sp_issuer:
      type: string
    oauth_login_oauth2_login_by:
      type: integer
    oauth_login_oauth2_attr1_name:
      type: string
    oauth_login_oauth2_entity_id:
      type: string
    oauth_login_oauth2_base_url : 
      type: string  
    oauth_login_oauth2_acs_url:
      type: string  
    oauth_login_oauth2_nameid_attr_map:
      type: string